//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulServiceClient.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IMulService")]
    public interface IMulService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMulService/Mult", ReplyAction="http://tempuri.org/IMulService/MultResponse")]
        int Mult(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMulService/Mult", ReplyAction="http://tempuri.org/IMulService/MultResponse")]
        System.Threading.Tasks.Task<int> MultAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMulServiceChannel : MulServiceClient.MyService.IMulService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MulServiceClient : System.ServiceModel.ClientBase<MulServiceClient.MyService.IMulService>, MulServiceClient.MyService.IMulService {
        
        public MulServiceClient() {
        }
        
        public MulServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MulServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MulServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MulServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Mult(int a, int b) {
            return base.Channel.Mult(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultAsync(int a, int b) {
            return base.Channel.MultAsync(a, b);
        }
    }
}
